### ISSUE TITLE
Question about NuGet/setup-nuget

### ISSUE THREAD

**Issue by sungam3r** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1048]
I see that each CD workflow uses 
```yaml
  - name: setup nuget
      uses: NuGet/setup-nuget@v1.0.5
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        nuget-version: latest
```

After that it executes 
```yaml
 - name: Publish <NAME_HERE> Health Check nuget
      run: dotnet nuget push ./artifacts/AspNetCore.HealthChecks.NAME.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate
```

but `dotnet nuget push` is a built-in dotnet CLI command. So why to bother with _setup nuget_ step in all CD workflows?
ping @carlosrecuero @unaizorrilla
