### ISSUE TITLE
Consul HealthCheck never fails 

### ISSUE THREAD

**Issue by conrad-roux** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1050]
**What happened**:
When adding health check on Consul it always passes the health check on the leader endpoint call. The response always returns a successful status code on the leader endpoint (.../v1/status/leader)

**What you expected to happen**:
When the leader pod is down the endpoint returns and empty string, but with a http status code of 200. This causes the health check to not fail, where I expected it to fail.

**How to reproduce it (as minimally and precisely as possible)**:
use the following Docker Compose to create the cluster

_docker-compose.yml_

```yaml
version: '3'

services:
  consul1:
    container_name: consul-server1
    image: consul:latest
    volumes:
     - ./config/server1.json:/consul/config/server.json:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul2:
    container_name: consul-server2
    image: consul:latest
    volumes:
     - ./config/server2.json:/consul/config/server.json:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"
  
  consul3:
    container_name: consul-server3
    image: consul:latest
    volumes:
     - ./config/server3.json:/consul/config/server.json:ro
    networks:
      - consul
    command: "agent -bootstrap-expect=3"

  consul-client:
    container_name: consul-client
    image: consul:latest
    volumes:
     - ./config/client.json:/consul/config/client.json:ro
    networks:
      - consul
    ports:
      - 8500:8500
    command: "agent"

networks:
  consul:
    driver: bridge
```

Create a _config_ directory and add the following 4 files into the directory.

_client.json_

```json
{
    "node_name": "consul-client",
    "server": false,
    "ui_config": {
      "enabled": true
    },
    "data_dir": "/consul/data",
    "addresses": {
      "http": "0.0.0.0"
    },
    "retry_join": ["consul-server1", "consul-server2", "consul-server3"],
    "encrypt": "<redacted value>",
    "verify_incoming": false,
    "verify_outgoing": false,
    "verify_server_hostname": false
  }
```
_server1.json_

```json
{
  "node_name": "consul-server1",
  "server": true,
  "ui_config": {
    "enabled": false
  },
  "data_dir": "/consul/data",
  "addresses": {
    "http": "0.0.0.0"
  },
  "retry_join": ["consul-server2", "consul-server3"],
  "encrypt": "<redacted value>",
  "verify_incoming": false,
  "verify_outgoing": false,
  "verify_server_hostname": false
}
```
_server2.json_

```json
{
  "node_name": "consul-server2",
  "server": true,
  "ui_config": {
    "enabled": false
  },
  "data_dir": "/consul/data",
  "addresses": {
    "http": "0.0.0.0"
  },
  "retry_join": ["consul-server1", "consul-server3"],
  "encrypt": "<redacted value>",
  "verify_incoming": false,
  "verify_outgoing": false,
  "verify_server_hostname": false
}
```
_server3.json_

```json
{
  "node_name": "consul-server3",
  "server": true,
  "ui_config": {
    "enabled": false
  },
  "data_dir": "/consul/data",
  "addresses": {
    "http": "0.0.0.0"
  },
  "retry_join": ["consul-server1", "consul-server2"],
  "encrypt": "<redacted value>",
  "verify_incoming": false,
  "verify_outgoing": false,
  "verify_server_hostname": false
}
```
Verify the leader node name with the UI:
_http://localhost:8500/ui/dc1/nodes_

get the leader node name:
`docker-compose ps --services`

kill the leader pod with docker:
`docker-compose stop <name of service for the leader node>`

Immediately after the leader node is killed do a call on the endpoint (http://localhost:8500/v1/status/leader) and it will return an empty string but with status code 200, suggesting it did not fail.

**Environment**:
Kubernetes

- Healthchecks version: 6.0.2
- Operative system: Alpine Linux
