### ISSUE TITLE
[Docker-UI]Using env names in docker stack

### ISSUE THREAD

**Issue by alefcarlos** [Xabaril/AspNetCore.Diagnostics.HealthChecks#147]
Hello!

When using xabarilcoding/healthchecksui with docker stack, the envs names break the process.

Why dont you remove ":" from env name ? It would solve!

If i run `docker stack deploy.....` without envs:

```yml
  healthapp:
    image: xabarilcoding/healthchecksui
    container_name: healthapp
    restart: always
    # environment:
    #   HealthChecks-UI:HealthChecks:0:Name: "web"
    #   HealthChecks-UI:HealthChecks:0:Uri: "http://web/healthz"
    ports:
      - "8083:80"
```

The healthapp k8s services is created:

![image](https://user-images.githubusercontent.com/5452336/55839234-8371a680-5afd-11e9-92a8-025a0720c261.png)

And if i run the same command with:

```yml
  healthapp:
    image: xabarilcoding/healthchecksui
    container_name: healthapp
    restart: always
    environment:
      HealthChecks-UI:HealthChecks:0:Name: "web"
      HealthChecks-UI:HealthChecks:0:Uri: "http://web/healthz"
    ports:
      - "8083:80"
```

Nothing from `healthapp` is created:

![image](https://user-images.githubusercontent.com/5452336/55839328-d6e3f480-5afd-11e9-84db-b34b59d790d2.png)

**Comment by unaizorrilla** [comment]
Hi @alefcarlos 

We already have a Docker Image for UI than you can configure. The latest image is for UI 2.2.27 

https://cloud.docker.com/u/xabarilcoding/repository/docker/xabarilcoding/healthchecksui

Also, you can get information about how configure environment variables on next doc.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/doc/ui-docker.md

Hope this help you!

Thanks 
Unai

**Comment by alefcarlos** [comment]
Yeah, and I'm using it !

But the env names is getting me in troubles. The ":" in the name.

Thanks!

**Comment by unaizorrilla** [comment]
Hi @alefcarlos 

Are you try the sample here:

docker run --name ui -p 5000:80 -e 'HealthChecks-UI:HealthChecks:0:Name=httpBasic' -e 'HealthChecks-UI:HealthChecks:0:Uri=http://the-healthchecks-server-path' -d xabarilcoding/healthchecksui:latest

**Comment by alefcarlos** [comment]
When I run using docker run everything is good ! Now, I'm trying to run using docker stack, to deploy in k8s. 

My docker-compose:

```yml
version: '3.3'

services:
  web:
    build: .
    image: demo-api
    container_name: aspnet-core-webapi
    restart: always
    deploy:
      replicas: 1
    environment:
      - JWT_ISS=http://localhost:8181/api/signup
      - JWT_AUD=demo.api
      - JWT_EXPIRATION=1800
      - MONGO_URI=mongodb://mongodb:27017/clinfy
      - MYSQL_CONNECTION=Server=mysqldb;Database=dbz;User=root;Password=root;
      - REDIS_URI=redis,name=Demo.Api,defaultDatabase=1
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq
    ports:
      - "8181:80"
    links:
      - mongodb
      - mysqldb
      - rabbitmq
      - redis
      - healthapp
    depends_on:
      - mongodb
      - mysqldb
      - rabbitmq
      - redis

  healthapp:
    image: xabarilcoding/healthchecksui
    container_name: healthapp
    restart: always
    environment:
      HealthChecks-UI_HealthChecks_0_Name: web
      HealthChecks-UI_HealthChecks_0_Uri: http://web/healthz
    ports:
      - "8083:80"

  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"

  mysqldb:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysqldb"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  redis:
    image: redis
    container_name: "redis"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
```
