### ISSUE TITLE
Hostname is not reachable (Docker)

### ISSUE THREAD

**Issue by NicolasREY69330** [Xabaril/AspNetCore.Diagnostics.HealthChecks#553]
**What happened**:
Hi,
I followed the current configuration sample https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.StorageProviders/Startup.cs#L38 provided in the current issue #540 

But at the end I get the following error when using the UI 
`IPv4 address 0.0.0.0 and IPv6 address ::0 are unspecified addresses that cannot be used as a target address. (Parameter 'hostName')`

![image](https://user-images.githubusercontent.com/50946960/83940681-4fb80c80-a7e6-11ea-9a87-6cdf8dfd171c.png)

The API works fine 
![image](https://user-images.githubusercontent.com/50946960/83940702-7118f880-a7e6-11ea-8236-dcdd16cdb7c4.png)

_**I'm pretty sure it's due to docker hostname which is not reacheable, but I can't figure out how to solve it.**_

**What you expected to happen**:
I was supposed to get the random healthy / unhealthy from the sample but not an error due to hostname reaching problem

**Source code sample**:
`Startup.cs` => `ConfigureServices`
![image](https://user-images.githubusercontent.com/50946960/83940802-05835b00-a7e7-11ea-849a-5fc0675c1dd4.png)

`Startup.cs` => `Configure`
![image](https://user-images.githubusercontent.com/50946960/83940794-f0a6c780-a7e6-11ea-9e01-1c04c0a4b28a.png)

I work with docker compose :

`docker-compose.yml`
```
  myservice:
    image: ${DOCKER_REGISTRY-}myservice
    build:
      context: .
      dockerfile: src/myservice/Dockerfile
```

`docker-compose.override.yml`
```
 myservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "50708:80"
      - "44345:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro    
```
**Environment**:

- .NET Core version 3.1
- Healthchecks version 3.1.1
- Operative system: Windows 10 Pro
- Others: Docker Desktop 2.3.0.3 with Linux containers
