### ISSUE TITLE
HealthChecks UI not displaying/writing history

### ISSUE THREAD

**Issue by tborozan** [Xabaril/AspNetCore.Diagnostics.HealthChecks#624]
**What happened**:

HealthChecks UI not displaying history

**What you expected to happen**:

Expect to see some info in details when an entry changes from Healthy to Unhealthy and vice versa. 

Currently, no history gets displayed.

![alt text](https://i.imgur.com/yvO0cmk.png)

These are the tables from my local db
[HealthCheckExecutionHistories](https://i.imgur.com/5VIMnXz.png)
[HealthCheckExecutionEntries](https://i.imgur.com/vksdlaI.png)

**How to reproduce it (as minimally and precisely as possible)**:

I used the Docker Compose sample from Docker Hub and added endpoints

```
version: "3.7"
services:
    healthchecks:
        image: xabarilcoding/healthchecksui
        depends_on:
            - sqlserver
        environment:
            - storage_provider=SqlServer
            - storage_connection=Server=sqlserver,1433;User Id=sa;Password=Password12!;Initial Catalog=DockerUI
            - Logging:LogLevel:Default=Debug
            - Logging:Loglevel:Microsoft=Warning
            - Logging:LogLevel:HealthChecks=Debug
            - HealthChecksUI__HealthChecks__0__Name=myname
            - HealthChecksUI__HealthChecks__0__Uri=myuri

        ports:
            - 5000:80
    sqlserver:
        image: microsoft/mssql-server-linux
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12!
        ports:
            - 1433:1433
```

**Anything else we need to know?**:

Database gets generated and all tables have entries except HealthCheckExecutionHistories
Tried making my own project with the UI and have the same issue.

**Environment**:

Docker

**Comment by CarlosLanderas** [comment]
Hello @tborozan. This is working good when the UI is deployed using the k8s operator so let me check your sample to see if something is missing

**Comment by tborozan** [comment]
I am not using k8s. I used the docker-compose file provided above locally to test and plan to deploy the container to Azure App Service. I actually already deployed the container to App Service as a test and still have the same issue. The container is configured using the env var in the post above.

**Comment by CarlosLanderas** [comment]
Yes I know is docker, that's why I want to check the differences between your deployment and the one that our operator performs to see where the problem could be. I'll take a look:)

**Comment by CarlosLanderas** [comment]
@tborozan does the remote healthcheck endpoint report  services state changes?. The HealthCheckExecutionHistories table is only filled when a service switches from healthy to unhealthy and viceversa

**Comment by tborozan** [comment]
Yes, I tried changing it. Both the whole service and the individual healthchecks but the table did not get filled.

**Comment by CarlosLanderas** [comment]
Hello @tborozan. I've tried it and it's working. Probably you are testing this with default Evaluation Time and its 180 secs. Use a lower setting with a random healthcheck to see it working faster

Try this:

```yaml
version: "3.7"
services:
    healthchecks:
        image: xabarilcoding/healthchecksui
        depends_on:
            - sqlserver
        environment:
            - storage_provider=SqlServer
            - storage_connection=Server=sqlserver,1433;User Id=sa;Password=Password12!;Initial Catalog=DockerUI
            - Logging:LogLevel:Default=Debug
            - Logging:Loglevel:Microsoft=Warning
            - Logging:LogLevel:HealthChecks=Debug
            - HealthChecksUI__EvaluationTimeInSeconds=5
            - HealthChecksUI__HealthChecks__0__Name=myname
            - HealthChecksUI__HealthChecks__0__Uri=http://host.docker.internal:8081/health

        ports:
            - 5000:80
    sqlserver:
        image: microsoft/mssql-server-linux
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12!
        ports:
            - 1433:1433
```

In the healthcheck endpoint use a random check:

```csharp
  public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers()
            .Services
            .AddHealthChecks()
            .AddCheck("check1", () => 
                DateTime.UtcNow.Second % 2 == 0 ? HealthCheckResult.Healthy() : HealthCheckResult.Unhealthy()
            );
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapHealthChecks("/health", new HealthCheckOptions {
                    Predicate = r => true,
                    ResponseWriter = UIResponseWriter.WriteHealthCheckUIResponse
                });
            });
        }
```

Result:

![image](https://user-images.githubusercontent.com/16475649/92573398-04e6de80-f286-11ea-8817-fe14492de75c.png)
