### ISSUE TITLE
How to use the K8S operator together with agic?

### ISSUE THREAD

**Issue by brechtvhb** [Xabaril/AspNetCore.Diagnostics.HealthChecks#633]
Is it possible to use the K8S operator together with agic?

In my other apps I have an ingress.yml which lets the application gateway know how to reach the app

example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coolservice-api-ingress
  namespace: global
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/request-timeout: "60"    
		
spec:
  rules:
  - http:
      paths:
      - path: /api/coolservice/*
        backend:
          serviceName: coolservice-api-service
          servicePort: 80
```

It is not entirely clear how I have to do this together with the operator which somehow already has options about what the UI path should be. Operators are a new concept for me.
Can anyone point me in the right direction?

**Comment by CarlosLanderas** [comment]
@brechtvhb let me try to reproduce this scenario and add it to the docs, I think it could help many people with that have this same doubts.

**Comment by brechtvhb** [comment]
I found a way to make it work with agic:

Heres the config of my healthchecks ui:

```
apiVersion: "aspnetcore.ui/v1"
kind: HealthCheck
metadata:
  name: healthchecks-ui
  namespace: healthchecks
spec:
  name: healthchecks-ui
  scope: Cluster
  servicesLabel: HealthChecks
  serviceType: ClusterIP
  uiPath: /health
  uiApiPath: /health/api
  uiResourcesPath: /health/static
  uiWebhooksPath: /health/webhooks
```

Here's my ingress YAML

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: healthchecks-ui-ingress
  namespace: healthchecks
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/request-timeout: "60"    
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "40"

spec:
  rules:
  - http:
      paths:
      - path: /health/*
        backend:
          serviceName: healthchecks-ui-svc
          servicePort: 80
      - path: /health
        backend:
          serviceName: healthchecks-ui-svc
          servicePort: 80         
```
