### ISSUE TITLE
ui-docker.md invalid image name in docker-compose example

### ISSUE THREAD

**Issue by ahryshchanka** [Xabaril/AspNetCore.Diagnostics.HealthChecks#666]
**What happened**: issue in documentation

**What you expected to happen**: example in ui-docker.md valid

**How to reproduce it (as minimally and precisely as possible)**: run code from [Sample Docker Compose area](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/doc/ui-docker.md#sample-docker-compose)

**Source code sample**:
```
version: "3.7"
services:
  healthchecks:
    image: healthchecksui
    depends_on:
      - sqlserver
    environment:
      - storage_provider=SqlServer
      - storage_connection=Server=sqlserver,1433;User Id=sa;Password=Password12!;Initial Catalog=DockerUI
      - Logging:LogLevel:Default=Debug
      - Logging:Loglevel:Microsoft=Warning
      - Logging:LogLevel:HealthChecks=Debug
    ports:
      - 5000:80
  sqlserver:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12!
    ports:
      - 1433:1433
```
invalid line `image: healthchecksui`
valid line `image: xabarilcoding/healthchecksui` prefix **xabarilcoding** added

**Anything else we need to know?**: only documentation fixes required

**Environment**: any

- .NET Core version: any
- Healthchecks version: any
- Operative system: any
- Others: --
